In [7]:
%matplotlib inline 
#有了matplotlib inline 就可以省掉plt.show()了
%load_ext autoreload
%autoreload 2

from __future__ import division
from imports import *
#import pylab #使用pylab模式，可以直接使用numpy、pandas和绘图，而不需要再次引入,会配置为使用你所指定的matplotlib gui后端，还会提供一种更接近于matlab的界面
#%pylab
from IPython.display import display_html
display_html("""<button onclick="$('.input, .prompt, .output_stderr, .output_error').toggle();">Toggle code</button>""", raw=True)
# 允许多行输出
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Toggle code

#### NumPy（Numerical Python）是高性能科学计算和数据分析的基础包
功能：
* ndarray，一个具有矢量算术运算和复杂广播能力的快速且节省空间的多维数组
* 用于对整租数据进行快速运算的标准数学函数
* 用于读写磁盘数据的工具以及用于操作内存映射文件的工具
* 线性代数、随机数生成以及傅里叶变换
* 用于集成由C、C++、Fortran等语言编写的代码的工具

## ndarray：一种多维数组对象

#### 是一个快速而灵活的大数据集容器，可以利用这种数组对整块数据执行一些数学运算，其语法跟标量元素之间的运算一样
ndarray 是一个通用的同构数据多维容器，也就是说，其中的所有元素必须是相同类型的，每个数组都有一个shape和一个dtype

#### 创建ndarray
使用array函数

In [3]:
data1 = [5.2,1,8,0,2]
arr1 = np.array(data1)
arr1

array([ 5.2,  1. ,  8. ,  0. ,  2. ])

In [10]:
# 嵌套序列会被转换为一个多维数组
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2
arr2.shape

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

(2, 4)

#### zeros创建爱你一个指定长度或形状的全0数组，ones是全1数组，empty创建一个没有任何具体值得数组

In [12]:
np.zeros(10)
np.zeros((3,6))

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])